### ISSUE TITLE
Not process data

### ISSUE THREAD

**Issue by vgorn** [mattcg/socks5-client#12]
I get data in this line - https://github.com/mattcg/socks5-client/blob/master/lib/Socket.js#L133
But then nothing happens.
Why?

Why this atttr-s is undefined:
	self.socket.parser = self.parser;
	self.socket.ondata = self.ondata;
https://github.com/mattcg/socks5-client/blob/master/lib/Socket.js#L137

**Comment by mattcg** [comment]
Hi @vgorn, what's the error message you're getting? How do you replicate the problem?
