### ISSUE TITLE
Using with request with non standard port causes TypeError

### ISSUE THREAD

**Issue by eostman** [mattcg/socks5-client#17]
When trying to make a GET request to an url of type https://url.com:8075 via `request`. 

```javascript
var Agent = require('socks5-https-client/lib/Agent');

request({
  method: 'GET',
  url: "https://url.com:8075",
  agentClass: Agent,
 }
```
Then this error is thrown `Failure with error: TypeError: Invalid port: 8075.`

The failure seems to be caused because the port number is passed in as a String, `request` seems to pass the port number as a string instead of as an integer.

**Comment by mattcg** [comment]
Thank you for reporting this. Please try an `npm update` and let me know if it works after that :)

**Comment by eostman** [comment]
Yes, it works now. Thank you!
