### ISSUE TITLE
what is it?

### ISSUE THREAD

**Issue by raitucarp** [mattcg/socks5-client#6]
```
Error: SOCKS connection failed. Connection refused.
     at Socket.socket.ondata (/home/apps/myapps/node_modules/socks5-http-client/node_modules/socks5-client/lib/socket.js:193:12)
     at TCP.onread (net.js:527:27)
```

I use tor service. is it because tor service timeout, or something wrong with socket.js? could you update this module and check the probability of bug for latest node?

**Comment by mattcg** [comment]
This package is now compatible with node v0.12.0. Will you try the latest version please? It's 1.0.0. You might have to update the version string in your package config.
