### ISSUE TITLE
socks authorization

### ISSUE THREAD

**Issue by asluchevskiy** [mattcg/socks5-client#8]
Hello, is it possible to add socks authorization support to your lib?

**Comment by Sironfoot** [comment]
+1 for this.

Trying to connect to a Socks5 proxy using "socks5-https-client" library, the proxy service requires a username/password.

**Comment by shiny** [comment]
+1

**Comment by mattcg** [comment]
Will you try the master branch? I've added authorisation support.

**Comment by Jevin23** [comment]
https://github.com/mattcg/socks5-client/pull/14

**Comment by mattcg** [comment]
@Jevin23 thank you, updated with that fix. Please re-test.
